BaSP-TG: Added controller, model, validations and routes for Employees.
BaSP-a2022/bestia-b-trackgenix-server pull request #14
Opened 2022-10-18 23:04 UTC by javierperezraffo

2022-10-19 00:14 UTC, HoracioDuarteOK commented on src/models/Employees.js
> +  email: { type: String, required: true },
You can add email:{ unique: true..

2022-10-19 00:14 UTC, HoracioDuarteOK commented on src/controllers/employees.js
> +      res.status(200).json({
status 201

2022-10-19 00:28 UTC, HoracioDuarteOK approved these changes

2022-10-19 00:42 UTC, Ignacio-Sormani commented on postman_collection.json
> +					"name": "/",
Add a name for each endpoint: GET ALL, GET BY ID, ADD, UPDATE and DELETE

2022-10-19 00:43 UTC, Ignacio-Sormani commented on postman_collection.json
> +							"raw": "localhost:3000/employees/634c94d68b20f4f1288dd4ef",
It should be "localhost:3000/employees/:id". Add the id as a param in postman

2022-10-19 00:44 UTC, Ignacio-Sormani commented on postman_collection.json
> +							"raw": "localhost:3000/employees/634c94d68b20f4f1288dd4ef",
Do the same por put and delete methods

2022-10-19 00:45 UTC, Ignacio-Sormani commented on postman_collection.json
>  {
Add a body example for post and put methods

2022-10-19 00:58 UTC, Ignacio-Sormani requested changes

2022-10-19 00:58 UTC, Ignacio-Sormani commented on src/controllers/employees.js
> +const getOne = (req, res) => {
All these functions are asynchronous. So you should use async with try/catch. Please take a look at you teammates PRs to find out how you should implement this

2022-10-19 00:58 UTC, Ignacio-Sormani commented on src/controllers/employees.js
>    const empId = req.params.id;
There is no need to store the employeeId in a const. You can just use it in line 5

2022-10-19 00:58 UTC, Ignacio-Sormani commented on src/controllers/employees.js
>    const employeeId = req.params.id;
There is no need to store the employeeId

2022-10-21 13:14 UTC, Ignacio-Sormani approved these changes

2022-10-21 14:58 UTC, merged