BaSP-TG-08: SuperAdmin crud with validations and postman collection
BaSP-a2022/bestia-b-trackgenix-server pull request #15
Opened 2022-10-18 23:30 UTC by MatiasPazConti

2022-10-18 23:39 UTC, javierperezraffo approved these changes

2022-10-19 00:32 UTC, Ignacio-Sormani requested changes

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.status(404).json({
If there are no superadmins that match the filters criteria, you should return:
a) Message: 'There are not superadmins', data: undefined, error: true, status: 404
b) Message: 'Superadmins list", data: [], error: false, status: 200
It's a project decision to choose option a or b. In this case I think the best option should be the first one

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: 'An error ocurried',
It should say "An error occurred"

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      data: foundSuperAdmin,
Data should be undefined

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      error: false,
Error should be true if status is 4XX

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.json({
Status is missing

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.json({
Status is missing

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    const result = await newSuperAdmin.save();
I think there is no need to make this: await newSuperAdmin.save();

Can you check if it is necessary or not?

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.json({
Status is missing

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: 'An error ocurried',
Fix message

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    const superAdminId = req.params.id;
You don't need to store the id in a const

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      return res.status(404).json({
If status is 4XX, error should be true

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.json({
Status is missing

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: `Super-Admin with id ${superAdminId} edited`,
Don't need to show the superAdminId in the message. It will be sent in the data of the response

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: 'An error ocurried',
Fix message

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: `Super-Admin with id ${superAdminId} deleted`,
Don't need to show the superAdminId in the message. It will be sent in the data of the response

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.status(200).json({
It should be error 204

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    return res.json({
Status is missing

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +      message: 'An error ocurried',
Fix the message

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/controllers/super-admins.js
> +    const superAdminId = req.params.id;
You don't need to store the id in a const

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/index.js
>  // use "require" to import JSON files
Remove this comment in the code

2022-10-19 00:32 UTC, Ignacio-Sormani commented on src/validations/super-admins.js
> +      message: `There was an error: ${validation.error.details[0].message}`,
What do you think about specifying "There was a validation error: ..."

If you consider that changing it is a good decision, move forward with it. If not, don't update it. It's up to you.

2022-10-19 00:32 UTC, Ignacio-Sormani commented on postman_collection.json
> +									"key": "email",
Just keep one email in the query params for getAll method

2022-10-19 01:44 UTC, MatiasPazConti commented on src/controllers/super-admins.js
> +    return res.status(200).json({
If I change status(200) with status(204), the DELETE function doesn't return any response

2022-10-19 02:23 UTC, renzopimentel approved these changes

2022-10-19 22:43 UTC, javierperezraffo approved these changes

2022-10-20 00:21 UTC, Ignacio-Sormani approved these changes

2022-10-20 02:04 UTC, merged