BaSP-TG-06: Project methods and postman collection
BaSP-a2022/bestia-b-trackgenix-server pull request #17
Opened 2022-10-19 01:46 UTC by Romimonde

2022-10-19 02:10 UTC, MatiasPazConti approved these changes

2022-10-19 02:25 UTC, renzopimentel commented on postman_collection.json
> +							"raw": "localhost:3000/projects/634f0e4e632e8558d15deb7c",
put projects/:id instead of the id

2022-10-19 22:59 UTC, javierperezraffo approved these changes

2022-10-20 16:53 UTC, Ignacio-Sormani requested changes

2022-10-21 02:06 UTC, merged