BaSP-TG-19: Time sheets seeds and test
BaSP-a2022/bestia-b-trackgenix-server pull request #24
Opened 2022-10-25 13:20 UTC by javierperezraffo

2022-10-26 17:55 UTC, Ignacio-Sormani requested changes

2022-10-26 17:55 UTC, Ignacio-Sormani commented on src/seeds/time-sheets.js
> +// Generate ObjectId on https://observablehq.com/@hugodf/mongodb-objectid-generator
Remove comment

2022-10-26 23:39 UTC, HoracioDuarteOK approved these changes

2022-10-27 00:28 UTC, Ignacio-Sormani approved these changes

2022-10-27 00:30 UTC, merged