BaSP-TG-16: Super admins test and seed
BaSP-a2022/bestia-b-trackgenix-server pull request #25
Opened 2022-10-25 19:10 UTC by Romimonde

Please checkkk :)

2022-10-25 19:52 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +    expect(response.body.error).toBeTruthy();
In case of **status 400 with invalid id** use:
`expect(response.body.error.name).toBe('CastError')`

2022-10-25 19:52 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +    expect(response.body.message).toBe('There was a validation error: "password" length must be at least 8 characters long');
This is just the case of invalid password. If you want to cover all validation errors, it's better to use:
`expect(response.body.message).toMatch(/There was a validation error:/)`
and every validation error that start with "**There was a validation error:**" will count

2022-10-25 19:52 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +  test('should fail because of super ademin not found', async () => {
Fix **ademin** with **admin**

2022-10-25 19:52 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +    expect(response.body.error).toBeTruthy();
Status 400 with invalid id should be:
`expect(response.body.error.name).toBe('CastError')`

2022-10-25 19:52 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +  });
`expect(response.message)` is missing

2022-10-25 20:01 UTC, MatiasPazConti commented on src/tests/super-admins.test.js
> +  test('should failed because of invalid email', async () => {
If you cover all the validation error with the previously explained method, this test could be unnecesary... (But, it'll be better if you ask Nachanga o Bestia first)

2022-10-25 20:59 UTC, MatiasPazConti approved these changes

2022-10-25 22:49 UTC, Ignacio-Sormani requested changes

2022-10-25 22:49 UTC, Ignacio-Sormani commented on src/seeds/super-admins.js
> +  password: 'ZIbWT7',
Update password to have a length of at least 8 characters

2022-10-25 22:49 UTC, Ignacio-Sormani commented on src/seeds/super-admins.js
> +  password: 'Tge7HmA',
Update password to have a length of at least 8 characters

2022-10-25 22:49 UTC, Ignacio-Sormani commented on src/seeds/super-admins.js
> +  password: 'Jtkx8M',
Update password to have a length of at least 8 characters

2022-10-25 23:59 UTC, HoracioDuarteOK approved these changes

2022-10-26 00:06 UTC, renzopimentel approved these changes

2022-10-26 00:24 UTC, Ignacio-Sormani approved these changes

2022-10-26 00:35 UTC, merged